# Generated by Django 5.1.2 on 2024-10-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.AddField(
            model_name='producto',
            name='clasificacion_riesgo',
            field=models.CharField(default='bajo', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(default='Funcionando', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_adquisicion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='informacion_adicional',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='mantenimiento_calibracion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(default='Desconocido', max_length=200),
        ),
        migrations.AddField(
            model_name='producto',
            name='modelo',
            field=models.CharField(default='Sin especificar', max_length=200),
        ),
        migrations.AddField(
            model_name='producto',
            name='numero_serie',
            field=models.CharField(default='No disponible', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='objetivo_uso',
            field=models.CharField(default='Uso general', max_length=300),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
