# Generated by Django 5.1.2 on 2024-10-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_producto_marca_alter_producto_modelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='clasificacion_riesgo',
            field=models.CharField(default='bajo', max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(default='Funcionando', max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='modelo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='numero_serie',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='objetivo_uso',
            field=models.CharField(max_length=255),
        ),
    ]
