# Generated by Django 5.1.2 on 2024-10-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_producto_clasificacion_riesgo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='anio_adquisicion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_adquisicion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
