# Generated by Django 5.1.2 on 2024-10-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_producto_anio_adquisicion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='clasificacion_riesgo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
