# Generated by Django 5.1.2 on 2024-10-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_producto_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
